### ISSUE TITLE
요구사항 [new!!]

### ISSUE THREAD

**Issue by gimhanul** [soolung/dj-simblue#8]
- [x] 날짜 입력하는 거 label 클릭시 나오도록 변경
- [x] DropItem import 안 됨
- [x] 밷지 색깔 바꿀 수 있게 수정 + 가운데 정렬
    <img width="104" alt="image" src="https://github.com/soolung/dj-simblue/assets/80656733/0226cef5-128d-491b-a49a-4ef60af721d3">
- [x] Icon 없는 거 추가(필요한 건 do not disturb)...
    <img width="577" alt="image" src="https://github.com/soolung/dj-simblue/assets/80656733/07e54a06-c607-4e35-86a7-96e6c0e7bae2">

**Comment by kimhyerin0909** [comment]
끝나써요
